apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.fullName }}-http
spec:
  parentRefs:
    {{- range .Values.gateway.parentRefs }}
    - name: {{ .name }}
      namespace: {{ .namespace }}
      sectionName: {{ .sectionName }}
    {{- end }}
  hostnames:
    - {{ .Values.nginx.conf.serverName }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.pathPrefix }}
      backendRefs:
        - name: {{ .Values.fullName }}-service
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.nginx.conf.port }}
    {{- with .Values.gateway.additionalRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
