apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}-service
spec:
  selector:
    app: {{ .Values.fullName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
